[[OpenImageIO]]
arch = "aarch64"
git-tree-sha1 = "7af5762c83add73fa1b1429a80d415ad2f23a186"
os = "macos"

    [[OpenImageIO.download]]
    sha256 = "6b31956347ad1484f1ef08254ecb04d32cd0364d889433f2b84e1e2b2aff9f92"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.aarch64-apple-darwin.tar.gz"
[[OpenImageIO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fa93e77b2b99b02cb502f625f63941fdb4565bf"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "2bdafa6391b3eecc33e85491dab29a2996132c4fa67633e5fd7fdf4b4b829a97"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenImageIO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7b9e2c836786d97801e1db3cba568f1b92f5845"
libc = "musl"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "1be32bbeb4453c02a8ca8e38b17782e6f572dc06b55b4883c56dc25a2d0b4d56"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.aarch64-linux-musl-cxx11.tar.gz"
[[OpenImageIO]]
arch = "aarch64"
git-tree-sha1 = "770626a834b46711f1c6ca69ee818ffc3df52086"
os = "freebsd"

    [[OpenImageIO.download]]
    sha256 = "128d3aeaea888388ca915431fb6672907d66d6161f744f953bad747760de48cf"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.aarch64-unknown-freebsd.tar.gz"
[[OpenImageIO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "919368ae4a51fee2ee165fda9efce2171e890841"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "04eaac52d1f5b41379edb4e1faaf735e342d9657890bfc450fc4714feeb13d8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenImageIO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6f0aa4d3be0e50af9ed40b6fb484b2d626a68a9"
libc = "musl"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "1655e96550ddc64466d780d378e68af1c1d0d8f2898e127c889a0496f4ed9b58"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[OpenImageIO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45906a6ec744da5a3829a1dfa34b29029bba7563"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "7164ff86079de1ccac4c8bef4ca7e4077876bbabf60ea110cf586646b9182826"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenImageIO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b903a078b705272b518b69436856f94bb23c49fa"
libc = "musl"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "2cc6871c7bfc078b49b15d9f82d8a5d3dd6ea07b923c5d1224abff1b07296d89"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenImageIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f2ab61509ec523c8de300095f6900c36e574403"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "06c9d877821a64370f77613daab7217068b675020b90e6e631a9762ced1fa958"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.i686-linux-gnu-cxx11.tar.gz"
[[OpenImageIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2fb6d69b8679c25695e027c0400aeadf0ea7a8e"
libc = "musl"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "dfaf2203f75d5ef383ba11ae7f35f1fe72a69161ae7a62f6ccca7bcadda0daf0"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.i686-linux-musl-cxx11.tar.gz"
[[OpenImageIO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be19afc14ad8fd2cbb48c3eed06d965a341f4c60"
os = "windows"

    [[OpenImageIO.download]]
    sha256 = "4d62b558eee32d65640bd415b93695d63d170120397b8bf0cba2f3d742dd09c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.i686-w64-mingw32-cxx11.tar.gz"
[[OpenImageIO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ceb732011f9fe3d2f9353ea464c1e8fc5e30cedb"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "78ee256d2fdb7bc875753640b6d8582fc96616832fa3073b3707676dcd1991a7"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OpenImageIO]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08a58240aa90dac3a5949916dc7b38acafec9964"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "00d22102e0732154251487447788b977578fec7d55d8466fd33c463724c3c26a"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenImageIO]]
arch = "x86_64"
git-tree-sha1 = "02ca51263f0f2dd442ccc5401ef01093f801f310"
os = "macos"

    [[OpenImageIO.download]]
    sha256 = "b82b1123a4356c756c21317ca2ca1f20d297ffd394610a45bbdc672e7c7f1799"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.x86_64-apple-darwin.tar.gz"
[[OpenImageIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2663ef266e14812387528ee2c2ce41a3beb07c8"
libc = "glibc"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "84a30d134b1592e1b1e76e4af87fa2f0d6f7e7ae3c78bcbe555742c51748d077"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenImageIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e1eca8528948791dde8c25bd7e7a3616d7acbbe"
libc = "musl"
os = "linux"

    [[OpenImageIO.download]]
    sha256 = "1a7ef92ec6b489b15a49e6e7816a8f013ec114ce3918f59ee6c8bd79e23594d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.x86_64-linux-musl-cxx11.tar.gz"
[[OpenImageIO]]
arch = "x86_64"
git-tree-sha1 = "0ba51f426ecd566603b11153b520526a22b383bc"
os = "freebsd"

    [[OpenImageIO.download]]
    sha256 = "4e5c3b6bc6803017a8dd420c1e71007a584f8ec3f2922904e360175db1b75200"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.x86_64-unknown-freebsd.tar.gz"
[[OpenImageIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f99462a660d701390743196660304edc9627fed6"
os = "windows"

    [[OpenImageIO.download]]
    sha256 = "3ff79969e39158adbf5e7e43b27677f3ccb1b4165ba1d60be8ff5ad2ebacd485"
    url = "https://github.com/JuliaBinaryWrappers/OpenImageIO_jll.jl/releases/download/OpenImageIO-v3.1.8+0/OpenImageIO.v3.1.8.x86_64-w64-mingw32-cxx11.tar.gz"
