name = "OpenImageIO_jll"
uuid = "fd470f6e-6842-5666-8cbd-b5630dfbbd08"
version = "3.1.8+0"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
pugixml_jll = "ef860afa-341e-548b-93de-15e6b165854a"
OpenEXR_jll = "18a262bb-aa17-5467-a713-aee519bc75cb"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
libwebp_jll = "c5f90fcd-3b7e-5836-afba-fc50a0988cb2"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
OpenColorIO_jll = "4dcc563d-31b5-562a-a66a-bda255b7e226"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"
Giflib_jll = "59f7168a-df46-5410-90c8-f2779963d0ec"
OpenJpeg_jll = "643b3616-a352-519d-856d-80112ee9badc"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"

[compat]
Zlib_jll = "1.2.12"
Libdl = "< 0.0.1, 1"
FFMPEG_jll = "8.0.1"
JpegTurbo_jll = "3.1.4"
pugixml_jll = "1.15.0"
OpenEXR_jll = "~3.4.4"
FreeType2_jll = "2.13.4"
libwebp_jll = "1.6.0"
Libtiff_jll = "4.7.2"
OpenColorIO_jll = "2.5.0"
Giflib_jll = "5.2.3"
JLLWrappers = "1.7.0"
OpenJpeg_jll = "2.5.4"
boost_jll = "=1.87.0"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
libpng_jll = "1.6.53"
